[package]
name = "solana-qos-cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
que = { workspace = true }
solana-qos-common = { workspace = true }
solana-qos-core = { workspace = true }